SELECT ITEMS.WEIGHT, ITEMS.DESCRIPTION FROM ITEMS
JOIN(SELECT MIN(ITEMS.WEIGHT) AS MIN_WEIGHT FROM ITEMS) AS M
ON ITEMS.WEIGHT = MIN_WEIGHT;



SELECT WNAME, CITIES.CITY, CITIES.ID
FROM CITIES
JOIN WAREHOUSES ON WAREHOUSES.CITY_ID = CITIES.ID
WHERE CITIES.CITY = 'Pune';


SELECT CUSTOMER.CNAME, CUSTOMER.CID, ITEMS.DESCRIPTION, ITEMS.COST, ORDER_ITEMS.QUANTITY
FROM CUSTOMER
JOIN ORDERS ON ORDERS.CUSTOMER_INFO = CUSTOMER.CID
JOIN ORDER_ITEMS ON ORDER_ITEMS.OID = ORDERS.OID
JOIN ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO
WHERE CUSTOMER.CNAME = 'Mr Patil';



SELECT WAREHOUSES.WID, WAREHOUSES.WNAME, COUNT(STORES.SID) AS STORE_COUNT FROM WAREHOUSES
LEFT JOIN STORES ON WAREHOUSES.WID = STORES.STORE_LOC
GROUP BY WAREHOUSES.WID
HAVING COUNT(STORES.SID) = (
SELECT MAX(STORE_COUNT) AS MAX_STORE
FROM (
SELECT WAREHOUSES.WID, COUNT(STORES.SID) AS STORE_COUNT FROM WAREHOUSES
LEFT JOIN STORES ON WAREHOUSES.WID = STORES.STORE_LOC
GROUP BY WAREHOUSES.WID
) AS WAREHOUSE_STORES
);

SELECT ITEMS.ITEMNO, ITEMS.DESCRIPTION, COUNT(*) AS ORDER_COUNT FROM ITEMS
JOIN ORDER_ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO
GROUP BY ITEMS.ITEMNO
ORDER BY ORDER_COUNT ASC
LIMIT 1;

SELECT CUSTOMER.CID, CUSTOMER.CNAME, ORDERS.OID, ITEMS.DESCRIPTION, ITEMS.COST, ORDER_ITEMS.QUANTITY
FROM CUSTOMER
JOIN ORDERS ON ORDERS.CUSTOMER_INFO = CUSTOMER.CID
JOIN ORDER_ITEMS ON ORDER_ITEMS.OID = ORDERS.OID
JOIN ITEMS ON ITEMS.ITEMNO = ORDER_ITEMS.ITEMNO;